// <auto-generated />
using System;
using EMR.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMR.Migrations
{
    [DbContext(typeof(emrDbContext))]
    [Migration("20210414135716_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMR.Models.DOCTORS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CERTIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOCTOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOCTOR_SEX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE_NO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DOCTORS");
                });

            modelBuilder.Entity("EMR.Models.PATIENTS", b =>
                {
                    b.Property<string>("MOBILE_NUMBER")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<string>("PATIENTS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATIENTS_SEX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MOBILE_NUMBER");

                    b.ToTable("PATIENTS");
                });

            modelBuilder.Entity("EMR.Models.PRESCRIPTIONS", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AGE_DAYS")
                        .HasColumnType("int");

                    b.Property<int>("AGE_MONTH")
                        .HasColumnType("int");

                    b.Property<int>("AGE_YEAR")
                        .HasColumnType("int");

                    b.Property<string>("BLOOD_GROUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOCTORS_ID")
                        .HasColumnType("int");

                    b.Property<string>("INSTRUCTIONS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATIENTS_MOBILE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATIENTS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATIENTS_SEX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PRESCRIBE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PRESCRIPTIONS_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROBLEMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_PRESCRIPTIONS_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("REQUIRED_ADMISSION")
                        .HasColumnType("bit");

                    b.Property<string>("TEMPERATURE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VISIT_FEES")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("VISIT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEIGHT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PRESCRIPTIONS");
                });

            modelBuilder.Entity("EMR.Models.PRESCRIPTIONS_DRUGS", b =>
                {
                    b.Property<long>("PRESCRIPTIONS_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("LINE_NO")
                        .HasColumnType("int");

                    b.Property<int>("DRUGS_ID")
                        .HasColumnType("int");

                    b.Property<string>("DRUGS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DURATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FREQUENCY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRESCRIPTIONS_ID", "LINE_NO")
                        .HasName("PK_PRESCRIPTIONS_DRUGS");

                    b.ToTable("PRESCRIPTIONS_DRUGS");
                });

            modelBuilder.Entity("EMR.Models.PRESCRIPTIONS_INVES", b =>
                {
                    b.Property<long>("PRESCRIPTIONS_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("LINE_NO")
                        .HasColumnType("int");

                    b.Property<string>("INSTRUCTIONS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INVESTIGATIONS_ID")
                        .HasColumnType("int");

                    b.Property<string>("INVESTIGATIONS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_DIAGNOSTICS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRESCRIPTIONS_ID", "LINE_NO")
                        .HasName("PK_PRESCRIPTIONS_INVES");

                    b.ToTable("PRESCRIPTIONS_INVES");
                });

            modelBuilder.Entity("EMR.Models.PRESCRIPTIONS_DRUGS", b =>
                {
                    b.HasOne("EMR.Models.PRESCRIPTIONS", "PRESCRIPTIONS")
                        .WithMany("PRESCRIPTIONS_DRUGS")
                        .HasForeignKey("PRESCRIPTIONS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRESCRIPTIONS");
                });

            modelBuilder.Entity("EMR.Models.PRESCRIPTIONS_INVES", b =>
                {
                    b.HasOne("EMR.Models.PRESCRIPTIONS", "PRESCRIPTIONS")
                        .WithMany("PRESCRIPTIONS_INVES")
                        .HasForeignKey("PRESCRIPTIONS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRESCRIPTIONS");
                });

            modelBuilder.Entity("EMR.Models.PRESCRIPTIONS", b =>
                {
                    b.Navigation("PRESCRIPTIONS_DRUGS");

                    b.Navigation("PRESCRIPTIONS_INVES");
                });
#pragma warning restore 612, 618
        }
    }
}
