// <auto-generated />
using System;
using EMR.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMR.Migrations
{
    [DbContext(typeof(emrDbContext))]
    [Migration("20210413132207_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMR.Models.DOCTORS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CERTIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOCTOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOCTOR_SEX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE_NO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DOCTORS");
                });

            modelBuilder.Entity("EMR.Models.PATIENTS", b =>
                {
                    b.Property<string>("MOBILE_NUMBER")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<string>("PATIENTS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATIENTS_SEX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MOBILE_NUMBER");

                    b.ToTable("PATIENTS");
                });
#pragma warning restore 612, 618
        }
    }
}
